source "https://rubygems.org"

# GitHub Pages gem includes Jekyll and common plugins
gem "github-pages", group: :jekyll_plugins

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]
