source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "just-the-docs", "0.8.2"

# GitHub Pages compatibility
gem "github-pages", group: :jekyll_plugins

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]

# Plugins
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
  gem "jekyll-seo-tag", "~> 2.8"
  gem "jekyll-sitemap"
end
